branches:
  only:
  - master
language: node_js
node_js:
  - "node"
services: mongodb
before_script:
  - sleep 15
  - mongo slohacks-backend-test --eval 'db.users.createIndex( { email: 1 }, { unique: true } );'
  - npm install -g standard
script:
  - standard "./src/**/*.js"
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: slohacks-backend-api
  on:
    branch: master