branches:
  only:
  - master
language: node_js
node_js:
  - 11
services: mongodb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - sleep 15
  - npm install -g standard
script:
  - standard "./src/**/*.js"
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: slohacks-backend-api
  on:
    branch: master