branches:
  only:
  - master
language: node_js
node_js:
  - 11
services: mongodb
before_install:
  - npm i -g
before_script:
  - sleep 15
  - npm install -g standard
script:
  - standard "./src/**/*.js"
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: slohacks-backend-api
  on:
    branch: master